eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8080/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: favoriteService
          uri: lb://FAVORITE-SERVICE
          predicates:
          - Path=/favorites/**
