server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: channelPayment
          uri: lb://CHANNEL-PAYMENT
          predicates:
            - Path=/favorites/**
            - Path=/transactions/**
            - Path=/services/**
