eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8080/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: channelPayment
          uri: lb://CHANNEL-PAYMENT
          predicates:
          - Path=/favorites/**
          - Path=/transactions/**
          - Path=/services/**
